const config = {
  title: "Pablo Ramos",
  description: "Frontend Developer",
  coverImage: "",
  avatar: "",
  project1Banner: "/valobrainBanner.jpg",
  project2Banner: "https://via.placeholder.com/300",
  project3Banner: "https://via.placeholder.com/300",
  project4Banner: "https://via.placeholder.com/300",
  project5Banner: "https://via.placeholder.com/300",
  project6Banner: "https://via.placeholder.com/300",
  project1Github: "https://github.com/pabloramoss/valo-brain",
  project2Github: "https://github.com/pabloramoss/my-blog",
  project3Github: "https://github.com/pabloramoss/portfolio",
  project4Github: "https://via.placeholder.com/300",
  project5Github: "https://via.placeholder.com/300",
  project6Github: "https://via.placeholder.com/300",
  project1Url: "https://valobrain.vercel.app/",
  project2Url: "https://via.placeholder.com/300",
  project3Url: "https://via.placeholder.com/300",
  project4Url: "https://via.placeholder.com/300",
  project5Url: "https://via.placeholder.com/300",
  project6Url: "https://via.placeholder.com/300",
  siteUrl: "https://pabloramos.vercel.app",
  twitter: "https://twitter.com/rpablo_dev",
  github: "https://github.com/pabloramoss",
  linkedin: "https://www.linkedin.com/",
  aboutTitle: "¿Quién soy?",
  hardTechTitle: "Habilidades técnicas",
  softTechTitle: "Habilidades blandas",
  futureTitle: "Planes a futuro",
  about: "Me dedico al desarrollo de aplicaciones web. Me especializo en desarrollo frontend con React. Me gusta involucrarme en proyectos nuevos, aprender nuevas tecnologías, resolver problemas complejos y optimizar procesos.",
  hardTech: "HTML, CSS, Javascript, Typescript, React, React-Testing-Library, Next.js, Chakra-UI, Framer-motion, Node.js, MongoDB, Firebase, Express, Git, Github, Figma, Photoshop",
  softTech: "Comunicación, trabajo en equipo, flexibilidad, creatividad, gestión del tiempo, planificación",
  future: "Mi objetivo es seguir especializándome en frontend y UI/UX. Otro objetivo es aprender todo lo relacionado con web3 como programación con Solidity, Web3.js, .Ether.js, etc.",
  telegram: "https://tttttt.me/pablooramoss",
  cv: ""
};

export default config;